### PR TITLE
chore: migrate-subgraph

### LINKED ISSUE #3: Migrate to TheGraph network
Update the variable `XDAI_GTCR_SUBGRAPH_URL` in the deployments

Blocked by https://github.com/kleros/gtcr-subgraph/issues/26
Resolves https://github.com/kleros/builder-baseline/issues/22

### PR DESCRIPTION
**Pull request by Harman-singh-waraich**
closes #3

### CODE REVIEW

**Review by kemuru — APPROVED** [review]
not sure why but the command `yarn start --mode fetch` does not work with the new subgraph, but thats probably out of scope of this PR, and up to @salgozino to fix later?

image

**Comment by salgozino** [comment]
> not sure why but the command `yarn start --mode fetch` does not work with the new subgraph, but thats probably out of scope of this PR, and up to @salgozino to fix later?
> 
> image

Most probably because with the studio api endpoints, the `Content-Application` header need to be defined as `application/json` in this [lines](https://github.com/kleros/tag-registry-rewards/blob/cb34b9c3e55d4a1026c7021226fb42544305a667/src/tag-fetch.ts#L35-L38)

**Comment by salgozino** [comment]
Pushed a fix for the issue @kemuru, please review again.

**Review by kemuru — APPROVED** [review]
perfect, lgtm

**Comment by Harman-singh-waraich** [comment]
> > not sure why but the command `yarn start --mode fetch` does not work with the new subgraph, but thats probably out of scope of this PR, and up to @salgozino to fix later?
> > image
> 
> Most probably because with the studio api endpoints, the `Content-Type` header need to be defined as `application/json` in this [lines](https://github.com/kleros/tag-registry-rewards/blob/cb34b9c3e55d4a1026c7021226fb42544305a667/src/tag-fetch.ts#L35-L38)

Yes, I must have overlooked adding that in some PR's.
Will go over the PR's to mkae sure it's set correctly.

Thanks for pointing out 🙌

**Pull request merged**
